#93 add get subscriptions and get subscribers methods
meetacy/sdk pull request #94
Opened 2024-03-07 22:10 UTC by y9Kap

2024-03-14 17:54 UTC, y9san9 requested changes

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/engine/requests/GetSubscribersRequest.kt
> +public data class GetSubscribersRequest(
Должно называться ListSubscribersRequest по аналогии с другими подобными методами

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/engine/requests/GetSubscriptionsRequest.kt
> +public data class GetSubscriptionsRequest(
Должно называться ListSubscriptionsRequest по аналогии с другими подобными методами

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/AuthorizedFriendsApi.kt
> +    public suspend fun subscriptions(
Метод должен быть в собственном api, также нужен дублёр, с названием paging

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/AuthorizedFriendsApi.kt
> +    public suspend fun subscribers(
Метод должен быть в собственном api, также нужен дублёр, с названием paging

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/AuthorizedFriendsApi.kt
> +    public fun listPaging(
Должно называться paging

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/AuthorizedFriendsApi.kt
> +    public fun subscribersPaging(
Должен быть в другом месте

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/AuthorizedFriendsApi.kt
> +    public fun subscriptionsPaging(
Должен быть в другом месте

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/FriendsApi.kt
> +    public suspend fun subscriptions(
Метод должен быть в собственном api, также нужен дублёр, с названием paging

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/FriendsApi.kt
> +    public suspend fun subscribers(
Метод должен быть в собственном api, также нужен дублёр, с названием paging

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/FriendsApi.kt
> +    public fun listPaging(
Должен называться просто paging

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/FriendsApi.kt
> +    public fun subscribersPaging(
Метод должен быть в другом месте

2024-03-14 17:54 UTC, y9san9 commented on api/src/commonMain/kotlin/app/meetacy/sdk/friends/FriendsApi.kt
> +    public fun subscriptionsPaging(
Метод должен быть в другом месте

2024-03-15 19:56 UTC, y9Kap reviewed
Жесть мощно. Кстати, я еще не знал, что надо и в репозитории юзеров  тоже добавлять новые методы

2024-03-16 13:39 UTC, merged